#!/usr/bin/env python3
"""Tests for insert_engine module."""
import os
import tempfile
import shutil
import pytest
from pathlib import Path
from insert_engine import InsertEngine

FIXTURES = Path(__file__).parent / 'fixtures'


class TestInsertEngineSmoke:
    """Smoke test to verify imports work."""

    def test_import(self):
        engine = InsertEngine()
        assert engine is not None


class TestDetectFormat:
    """Test format detection for various file types."""

    def test_codex_yaml_extension(self):
        """B2: .codex.yaml files must be detected as codex-yaml."""
        engine = InsertEngine()
        result = engine.detect_format(str(FIXTURES / 'sample.codex.yaml'))
        assert result == 'codex-yaml'

    def test_codex_yml_extension(self):
        """B2: .codex.yml files must be detected as codex-yaml."""
        engine = InsertEngine()
        with tempfile.NamedTemporaryFile(suffix='.codex.yml', mode='w', delete=False) as f:
            f.write(open(FIXTURES / 'sample.codex.yaml').read())
            tmp_path = f.name
        try:
            result = engine.detect_format(tmp_path)
            assert result == 'codex-yaml'
        finally:
            os.unlink(tmp_path)

    def test_codex_lite_extension(self):
        """Markdown with frontmatter detected as codex-lite."""
        engine = InsertEngine()
        result = engine.detect_format(str(FIXTURES / 'sample-lite.md'))
        assert result == 'codex-lite'

    def test_plain_markdown(self):
        """Plain markdown without frontmatter detected as markdown."""
        engine = InsertEngine()
        result = engine.detect_format(str(FIXTURES / 'sample-plain.md'))
        assert result == 'markdown'


class TestInsertCodexLineBased:
    """Test line-based YAML insertion (fallback path)."""

    def setup_method(self):
        self.tmpdir = tempfile.mkdtemp()

    def teardown_method(self):
        shutil.rmtree(self.tmpdir)

    def _make_codex(self, body_text):
        """Create a codex file with given body content."""
        indented = '\n'.join('  ' + line for line in body_text.split('\n'))
        content = f"type: chapter\nname: \"Test Chapter\"\nbody: |\n{indented}\nchildren: []\n"
        path = os.path.join(self.tmpdir, 'test.codex.yaml')
        with open(path, 'w') as f:
            f.write(content)
        return path

    def test_body_with_colons_not_treated_as_yaml_key(self):
        """B3: Body text containing colons must not be mistaken for YAML keys."""
        body = 'She said: "hello"\n\nnote: this is body text\n\nEnd of chapter.'
        path = self._make_codex(body)

        engine = InsertEngine()
        # Force line-based path
        engine._insert_codex = engine._insert_codex_line_based

        result = engine.insert(
            file_path=path,
            content="INSERTED TEXT",
            line_number=3,
            insert_after=True,
            create_backup=False,
            add_markers=False
        )

        assert result.success
        with open(path) as f:
            content = f.read()
        assert 'INSERTED TEXT' in content
        assert 'children: []' in content  # Structure preserved

    def test_body_end_detected_by_dedent(self):
        """Body ends when indentation returns to top-level YAML key."""
        body = 'Line 1\nLine 2\nLine 3'
        path = self._make_codex(body)

        engine = InsertEngine()
        engine._insert_codex = engine._insert_codex_line_based

        result = engine.insert(
            file_path=path,
            content="INSERTED",
            line_number=2,
            insert_after=True,
            create_backup=False,
            add_markers=False
        )

        assert result.success
        with open(path) as f:
            content = f.read()
        assert 'INSERTED' in content
        assert 'children: []' in content


class TestFindPendingInserts:
    """Test marker parsing resilience (B6)."""

    def setup_method(self):
        self.tmpdir = tempfile.mkdtemp()
        self.engine = InsertEngine()

    def teardown_method(self):
        shutil.rmtree(self.tmpdir)

    def test_standard_marker(self):
        """Standard markers generated by engine are found."""
        marker = self.engine.generate_insert_marker(
            content="Test content",
            source="test",
            instruction="after battle",
            confidence=0.85,
            matched_after="the battle ended"
        )
        path = os.path.join(self.tmpdir, 'test.md')
        with open(path, 'w') as f:
            f.write(f"Before.\n\n{marker}\n\nAfter.\n")

        pending = self.engine.find_pending_inserts(path)
        assert len(pending) == 1
        assert pending[0].content == "Test content"
        assert pending[0].confidence == 0.85

    def test_marker_with_extra_whitespace(self):
        """B6: Markers with extra whitespace between fields still parse."""
        marker_text = """<!-- INSERT
time: 2024-01-15T10:30:00Z
source: notepad

instruction: "after battle"
confidence: 0.85
matched_after: "the battle ended"
-->
Test content
<!-- /INSERT -->"""
        path = os.path.join(self.tmpdir, 'test.md')
        with open(path, 'w') as f:
            f.write(marker_text)

        pending = self.engine.find_pending_inserts(path)
        assert len(pending) == 1

    def test_marker_with_reordered_fields(self):
        """B6: Markers with different field order still parse."""
        marker_text = """<!-- INSERT
source: notepad
time: 2024-01-15T10:30:00Z
confidence: 0.85
instruction: "after battle"
matched_after: "ended"
-->
Content here
<!-- /INSERT -->"""
        path = os.path.join(self.tmpdir, 'test.md')
        with open(path, 'w') as f:
            f.write(marker_text)

        pending = self.engine.find_pending_inserts(path)
        assert len(pending) == 1
        assert pending[0].content == "Content here"


class TestAcceptRejectInserts:
    """Test accept/reject workflows (B1)."""

    def setup_method(self):
        self.tmpdir = tempfile.mkdtemp()
        self.engine = InsertEngine()

    def teardown_method(self):
        shutil.rmtree(self.tmpdir)

    def _make_file_with_inserts(self, num_inserts=3):
        """Create a markdown file with N pending INSERT markers."""
        lines = ["# Test Document\n\n"]
        for i in range(1, num_inserts + 1):
            marker = self.engine.generate_insert_marker(
                content=f"Insert content {i}",
                source="test",
                instruction=f"instruction {i}",
                confidence=0.8 + i * 0.05,
                matched_after=f"matched text {i}"
            )
            lines.append(f"Paragraph {i}.\n\n")
            lines.append(marker + "\n\n")

        lines.append("Final paragraph.\n")
        path = os.path.join(self.tmpdir, 'test.md')
        with open(path, 'w') as f:
            f.write(''.join(lines))
        return path

    def test_accept_all(self):
        """Accept all inserts removes all markers, keeps content."""
        path = self._make_file_with_inserts(3)
        count, errors = self.engine.accept_inserts(path, create_backup=False)
        assert count == 3
        assert errors == []
        with open(path) as f:
            content = f.read()
        assert '<!-- INSERT' not in content
        assert 'Insert content 1' in content
        assert 'Insert content 2' in content
        assert 'Insert content 3' in content

    def test_accept_specific_indices(self):
        """B1: Accept only indices [1, 3] keeps insert 2 as pending."""
        path = self._make_file_with_inserts(3)
        count, errors = self.engine.accept_inserts(path, indices=[1, 3], create_backup=False)
        assert count == 2
        with open(path) as f:
            content = f.read()
        assert 'Insert content 1' in content
        assert 'Insert content 3' in content
        # Insert 2 still has markers
        assert '<!-- INSERT' in content

    def test_reject_all(self):
        """Reject all inserts removes markers AND content."""
        path = self._make_file_with_inserts(2)
        count, errors = self.engine.reject_inserts(path, create_backup=False)
        assert count == 2
        with open(path) as f:
            content = f.read()
        assert '<!-- INSERT' not in content
        assert 'Insert content 1' not in content
        assert 'Insert content 2' not in content
        assert 'Final paragraph' in content

    def test_reject_specific_indices(self):
        """B1: Reject only index [2] keeps inserts 1 and 3."""
        path = self._make_file_with_inserts(3)
        count, errors = self.engine.reject_inserts(path, indices=[2], create_backup=False)
        assert count == 1
        with open(path) as f:
            content = f.read()
        assert 'Insert content 1' in content
        assert 'Insert content 2' not in content
        assert 'Insert content 3' in content


class TestInsertCodexYamlRuamel:
    """Test ruamel.yaml insertion path."""

    def setup_method(self):
        self.tmpdir = tempfile.mkdtemp()

    def teardown_method(self):
        shutil.rmtree(self.tmpdir)

    def _has_ruamel(self):
        try:
            import ruamel.yaml
            return True
        except ImportError:
            return False

    def test_markers_survive_ruamel_roundtrip(self):
        """B4: INSERT markers must not be corrupted by ruamel.yaml dump."""
        if not self._has_ruamel():
            pytest.skip("ruamel.yaml not installed")

        content = """type: chapter
name: "Test Chapter"
body: |
  Dawn broke over the frozen plains.

  Elena watched from the ramparts.

  Night fell and the camp grew silent.
children: []
"""
        path = os.path.join(self.tmpdir, 'test.codex.yaml')
        with open(path, 'w') as f:
            f.write(content)

        engine = InsertEngine()
        result = engine.insert(
            file_path=path,
            content="The scouts returned.",
            line_number=3,
            insert_after=True,
            source="test",
            instruction='after "the ramparts"',
            confidence=0.87,
            matched_after="Elena watched from the ramparts.",
            create_backup=False,
            add_markers=True
        )

        assert result.success

        # Markers must be parseable after ruamel roundtrip
        pending = engine.find_pending_inserts(path)
        assert len(pending) == 1
        assert pending[0].content == "The scouts returned."
        assert pending[0].confidence == 0.87

    def test_accept_after_ruamel_insert(self):
        """Markers inserted via ruamel must be acceptable."""
        if not self._has_ruamel():
            pytest.skip("ruamel.yaml not installed")

        content = """type: chapter
name: "Test"
body: |
  Line one.
  Line two.
children: []
"""
        path = os.path.join(self.tmpdir, 'test.codex.yaml')
        with open(path, 'w') as f:
            f.write(content)

        engine = InsertEngine()
        engine.insert(
            file_path=path,
            content="New line.",
            line_number=1,
            insert_after=True,
            create_backup=False,
            add_markers=True
        )

        count, errors = engine.accept_inserts(path, create_backup=False)
        assert count == 1
        assert errors == []


class TestInsertCodexLineBasedMarkers:
    """Test that line-based YAML insertion preserves findable markers (B8)."""

    def setup_method(self):
        self.tmpdir = tempfile.mkdtemp()

    def teardown_method(self):
        shutil.rmtree(self.tmpdir)

    def test_markers_findable_after_line_based_insert(self):
        """B8: Markers inserted via line-based fallback must be parseable."""
        content = """type: chapter
name: "Test Chapter"
body: |
  Dawn broke over the frozen plains.
  Elena watched from the ramparts.
  Night fell and the camp grew silent.
children: []
"""
        path = os.path.join(self.tmpdir, 'test.codex.yaml')
        with open(path, 'w') as f:
            f.write(content)

        engine = InsertEngine()
        # Force line-based path
        engine._insert_codex = engine._insert_codex_line_based

        result = engine.insert(
            file_path=path,
            content="Scouts returned at dusk.",
            line_number=2,
            insert_after=True,
            source="test",
            instruction="after ramparts",
            confidence=0.88,
            matched_after="Elena watched from the ramparts.",
            create_backup=False,
            add_markers=True
        )
        assert result.success

        # Markers must be findable even inside YAML body
        pending = engine.find_pending_inserts(path)
        assert len(pending) == 1, f"Expected 1 pending insert, found {len(pending)}"
        assert pending[0].content == "Scouts returned at dusk."

    def test_accept_after_line_based_insert(self):
        """Markers inserted via line-based path must be acceptable."""
        content = """type: chapter
name: "Test"
body: |
  Line one.
  Line two.
children: []
"""
        path = os.path.join(self.tmpdir, 'test.codex.yaml')
        with open(path, 'w') as f:
            f.write(content)

        engine = InsertEngine()
        engine._insert_codex = engine._insert_codex_line_based

        engine.insert(
            file_path=path,
            content="New line.",
            line_number=1,
            insert_after=True,
            create_backup=False,
            add_markers=True
        )

        count, errors = engine.accept_inserts(path, create_backup=False)
        assert count == 1
        assert errors == []


class TestInsertIntegration:
    """End-to-end integration tests."""

    def setup_method(self):
        self.tmpdir = tempfile.mkdtemp()
        self.engine = InsertEngine()

    def teardown_method(self):
        shutil.rmtree(self.tmpdir)

    def test_full_lifecycle_markdown(self):
        """Insert -> find -> accept lifecycle on markdown file."""
        src = str(FIXTURES / 'sample-lite.md')
        path = os.path.join(self.tmpdir, 'chapter.md')
        shutil.copy(src, path)

        # Insert with markers
        result = self.engine.insert(
            file_path=path, content="New scene content.",
            line_number=5, insert_after=True,
            source="test", instruction="after ramparts",
            confidence=0.9, matched_after="Elena watched from the ramparts.",
            create_backup=False, add_markers=True
        )
        assert result.success

        # Find pending
        pending = self.engine.find_pending_inserts(path)
        assert len(pending) == 1
        assert pending[0].content == "New scene content."

        # Accept
        count, errors = self.engine.accept_inserts(path, create_backup=False)
        assert count == 1
        assert errors == []

        # Verify clean
        pending_after = self.engine.find_pending_inserts(path)
        assert len(pending_after) == 0

        with open(path) as f:
            final = f.read()
        assert "New scene content." in final
        assert "<!-- INSERT" not in final

    def test_full_lifecycle_codex_yaml(self):
        """Insert -> find -> accept lifecycle on codex YAML file."""
        src = str(FIXTURES / 'sample.codex.yaml')
        path = os.path.join(self.tmpdir, 'chapter.codex.yaml')
        shutil.copy(src, path)

        result = self.engine.insert(
            file_path=path, content="Scouts returned at dusk.",
            line_number=3, insert_after=True,
            source="test", instruction="after scouts appeared",
            confidence=0.92, matched_after="the first scouts appeared",
            create_backup=False, add_markers=True
        )
        assert result.success

        pending = self.engine.find_pending_inserts(path)
        assert len(pending) == 1

        count, errors = self.engine.accept_inserts(path, create_backup=False)
        assert count == 1

        with open(path) as f:
            final = f.read()
        assert "Scouts returned at dusk." in final
        assert "<!-- INSERT" not in final

    def test_backup_creation(self):
        """Backups are created in .backups/ directory."""
        src = str(FIXTURES / 'sample-lite.md')
        path = os.path.join(self.tmpdir, 'chapter.md')
        shutil.copy(src, path)

        engine = InsertEngine(backup_dir=os.path.join(self.tmpdir, '.backups'))
        result = engine.insert(
            file_path=path, content="Test.",
            line_number=1, insert_after=True,
            create_backup=True, add_markers=False
        )

        assert result.success
        assert result.backup_path is not None
        assert os.path.exists(result.backup_path)


class TestFallbackBehavior:
    """Test that line-based fallback is used when ruamel is unavailable."""

    def setup_method(self):
        self.tmpdir = tempfile.mkdtemp()

    def teardown_method(self):
        shutil.rmtree(self.tmpdir)

    def test_falls_back_to_line_based_without_ruamel(self):
        """When ruamel.yaml is not installed, line-based insertion is used."""
        import unittest.mock

        content = """type: chapter
name: "Test"
body: |
  Line one.
  Line two.
children: []
"""
        path = os.path.join(self.tmpdir, 'test.codex.yaml')
        with open(path, 'w') as f:
            f.write(content)

        engine = InsertEngine()

        # Monkeypatch: make ruamel import fail inside _insert_codex
        with unittest.mock.patch.dict('sys.modules', {'ruamel': None, 'ruamel.yaml': None}):
            result = engine.insert(
                file_path=path,
                content="Fallback content.",
                line_number=1,
                insert_after=True,
                create_backup=False,
                add_markers=False
            )

        assert result.success
        with open(path) as f:
            output = f.read()
        assert "Fallback content." in output
